# Generated by Django 4.1.3 on 2023-04-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={
                "ordering": ("tax_type",),
                "verbose_name": "Tax",
                "verbose_name_plural": "Taxes",
            },
        ),
    ]
