# Generated by Django 4.1.3 on 2023-02-07 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
