# Generated by Django 4.1.3 on 2023-01-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="Vendor",
            new_name="vendor",
        ),
    ]
