# Generated by Django 4.1.3 on 2023-02-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_fooditem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=100),
        ),
    ]
